// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Book struct {
	ID          int64
	Title       string
	Author      sql.NullString
	Description sql.NullString
	EpubPath    string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt string
	UpdatedAt string
	UserID    string
	ExpiresAt string
	RevokedAt sql.NullString
}

type Thread struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	ThreadID  string
	UserID    string
	BookID    int64
}

type User struct {
	ID             string
	CreatedAt      string
	UpdatedAt      string
	Email          string
	HashedPassword string
}
